import { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import Nav from './components/Nav'
import Footer from './components/Footer'
import Icon from './components/Icon'
import { READING, readingRoute } from './data/reading'
import './App.css'
import './Reading.css'

// Same origin now: this site publishes its own feed (NEWS-AND-ANALYSIS-PRD.md).
// It used to fetch the bill tracker's copy cross-origin.
const NEWS_URL = '/api/news.json'

// A summary older than this stops being shown. Headlines keep their own dates, so they
// age honestly on their own; a stale digest does not.
const SUMMARY_MAX_AGE_MS = 72 * 60 * 60 * 1000

function formatRelativeDate(pubDate) {
  const date = new Date(pubDate)
  if (isNaN(date)) return ''
  const days = Math.floor((Date.now() - date) / (1000 * 60 * 60 * 24))
  if (days === 0) return 'Today'
  if (days === 1) return 'Yesterday'
  if (days < 7) return `${days} days ago`
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
}

function formatArticleDate(iso) {
  return new Date(`${iso}T00:00:00`).toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  })
}

function isFresh(lastUpdated) {
  const ts = new Date(lastUpdated).getTime()
  return Number.isFinite(ts) && Date.now() - ts < SUMMARY_MAX_AGE_MS
}

function NewsAndAnalysis() {
  const [data, setData] = useState(null)
  const [error, setError] = useState(false)
  // Advances on its own so the 72-hour cutoff still fires in a tab left open while the
  // feed is unreachable. Relying on the poll alone did not: a repeated fetch failure sets
  // the same error value, React skips the re-render, and the age is only re-checked when
  // something renders.
  const [, setClockTick] = useState(0)

  useEffect(() => {
    const tick = setInterval(() => setClockTick((n) => n + 1), 5 * 60 * 1000)
    return () => clearInterval(tick)
  }, [])

  useEffect(() => {
    let cancelled = false

    const load = () =>
      fetch(NEWS_URL, { cache: 'no-store' })
        .then((r) => {
          if (!r.ok) throw new Error('not found')
          return r.json()
        })
        .then((payload) => {
          if (cancelled) return
          setData(payload)
          setError(false)
        })
        .catch(() => {
          if (!cancelled) setError(true)
        })

    load()
    // A left-open tab would otherwise keep showing a summary past its 72 hours, and
    // would never learn that one was withheld — the freshness cutoff is evaluated at
    // render, so something has to prompt another render.
    const timer = setInterval(load, 10 * 60 * 1000)
    return () => {
      cancelled = true
      clearInterval(timer)
    }
  }, [])

  const showSummary = data?.summary && isFresh(data.lastUpdated)

  return (
    <div className="app">
      <Nav />
      <header className="page-hero">
        <div className="container">
          <h1>News &amp; analysis</h1>
        </div>
      </header>

      <section className="impact-section" id="news">
        <div className="container">
          <h2 className="section-heading">In the news</h2>

          {error && (
            <p className="news-status">
              The news feed couldn&apos;t load right now. Try again shortly.
            </p>
          )}
          {!error && !data && <p className="news-status">Loading the latest coverage…</p>}

          {showSummary && (
            <div className="news-summary">
              <p>{data.summary}</p>
              <span className="news-ai-disclosure">
                <Icon name="sparkles" size={13} />
                Summary generated by AI from the headlines below — read the original
                articles for full context.
              </span>
            </div>
          )}

          {data && data.articles?.length > 0 && (
            <>
              <p className="news-status news-status--meta">
                Updated {formatRelativeDate(data.lastUpdated)}
              </p>
              <ul className="news-list">
                {data.articles.map((article) => (
                  <li className="news-item" key={article.link}>
                    <a
                      className="news-item-title"
                      href={article.link}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      {article.title}
                      <Icon name="external-link" size={14} />
                    </a>
                    <span className="news-item-meta">
                      {article.source && <span>{article.source}</span>}
                      {article.source && article.pubDate && (
                        <span className="news-item-dot"> · </span>
                      )}
                      {article.pubDate && <span>{formatRelativeDate(article.pubDate)}</span>}
                    </span>
                  </li>
                ))}
              </ul>
            </>
          )}
          {data && !data.articles?.length && (
            <p className="news-status">No articles in the feed right now—check back soon.</p>
          )}
        </div>
      </section>

      {/* Long-form work stays visually separate from the aggregated headlines: these are
          credited pieces by named authors, not links with an AI digest on top. */}
      <section className="impact-section impact-section--alt" id="analysis">
        <div className="container">
          <h2 className="section-heading">Analysis &amp; essays</h2>
          <div className="preview-grid">
            {READING.map((piece) => (
              <Link
                className="preview-card preview-card-live"
                to={readingRoute(piece.slug)}
                key={piece.slug}
              >
                <span className="reading-card-meta">
                  By {piece.author} · {formatArticleDate(piece.date)}
                </span>
                <h3>{piece.title}</h3>
                <p>{piece.dek}</p>
              </Link>
            ))}
          </div>
        </div>
      </section>

      <Footer />
    </div>
  )
}

export default NewsAndAnalysis
