import { useState, useEffect } from 'react'
import Nav from './components/Nav'
import Footer from './components/Footer'
import Icon from './components/Icon'
import './App.css'

const NEWS_URL = 'https://billtracker.representdc.org/api/news.json'

function formatRelativeDate(pubDate) {
  const date = new Date(pubDate)
  if (isNaN(date)) return ''
  const days = Math.floor((Date.now() - date) / (1000 * 60 * 60 * 24))
  if (days === 0) return 'Today'
  if (days === 1) return 'Yesterday'
  if (days < 7) return `${days} days ago`
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
}

function News() {
  const [data, setData] = useState(null)
  const [error, setError] = useState(false)

  useEffect(() => {
    fetch(NEWS_URL)
      .then((r) => {
        if (!r.ok) throw new Error('not found')
        return r.json()
      })
      .then(setData)
      .catch(() => setError(true))
  }, [])

  return (
    <div className="app">
      <Nav />
      <header className="page-hero">
        <div className="container">
          <h1>Statehood in the news</h1>
          <p>Coverage from D.C. newsrooms and statehood organizations, updated daily.</p>
        </div>
      </header>
      <section className="impact-section">
        <div className="container">
          {error && (
            <p className="news-status">
              Couldn't load the news feed right now. It's fetched live from{' '}
              <a href="https://billtracker.representdc.org">the bill tracker</a>—try again shortly.
            </p>
          )}
          {!error && !data && <p className="news-status">Loading the latest coverage…</p>}
          {data && data.summary && (
            <div className="news-summary">
              <p>{data.summary}</p>
              <span className="news-ai-disclosure">
                <Icon name="sparkles" size={13} />
                Summary generated by AI from the headlines below — read the original
                articles for full context.
              </span>
            </div>
          )}
          {data && data.articles?.length > 0 && (
            <>
              <p className="news-status news-status--meta">
                Updated {formatRelativeDate(data.lastUpdated)}
              </p>
              <ul className="news-list">
                {data.articles.map((article, i) => (
                  <li className="news-item" key={i}>
                    <a
                      className="news-item-title"
                      href={article.link}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      {article.title}
                      <Icon name="external-link" size={14} />
                    </a>
                    <span className="news-item-meta">
                      {article.source && <span>{article.source}</span>}
                      {article.source && article.pubDate && <span className="news-item-dot"> · </span>}
                      {article.pubDate && <span>{formatRelativeDate(article.pubDate)}</span>}
                    </span>
                  </li>
                ))}
              </ul>
            </>
          )}
          {data && !data.articles?.length && (
            <p className="news-status">No articles in the feed right now—check back soon.</p>
          )}
        </div>
      </section>
      <Footer />
    </div>
  )
}

export default News
